"""indice de cobertura para saldos

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 17:41:19.755186
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_ledger",
            [
                "user_id",
                "occurred_on",
                "status",
                "type",
                "account_id",
                "to_account_id",
                "amount_cents",
                "deleted_at",
            ],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_ledger")

    # ### end Alembic commands ###
